/* Extract Database \\nbi-srv\C:\Lisemma\NBI_PFD.GDB */
CREATE DATABASE `NBI_PFD`  /* PAGE_SIZE 4096 */
;
USE `NBI_PFD`;


/*  External Function declarations */
/* DECLARE EXTERNAL FUNCTION ABS
DOUBLE PRECISION
RETURNS DOUBLE PRECISION BY VALUE
ENTRY_POINT `IB_UDF_abs` MODULE_NAME `ib_udf.dll`; */

/* DECLARE EXTERNAL FUNCTION DIV
INTEGER, INTEGER
RETURNS DOUBLE PRECISION BY VALUE
ENTRY_POINT `IB_UDF_div` MODULE_NAME `ib_udf.dll`; */

/* DECLARE EXTERNAL FUNCTION F_BLOBLINE
BLOB, INTEGER
RETURNS CSTRING(1024) CHARACTER SET NONE  FREE_IT
ENTRY_POINT `BlobLine` MODULE_NAME `PFD_UDFLib.dll`; */

/* DECLARE EXTERNAL FUNCTION F_DOLLARVAL
DOUBLE PRECISION
RETURNS CSTRING(254) CHARACTER SET NONE  FREE_IT
ENTRY_POINT `DollarVal` MODULE_NAME `PFD_UDFLib.dll`; */

/* DECLARE EXTERNAL FUNCTION F_ROUNDFLOAT
DOUBLE PRECISION, DOUBLE PRECISION
RETURNS DOUBLE PRECISION BY VALUE
ENTRY_POINT `RoundFloat` MODULE_NAME `PFD_UDFLib.dll`; */

/* Domain definitions */
/* CREATE DOMAIN BLOB AS BLOB SUB_TYPE TEXT SEGMENT SIZE 80;
 *//* CREATE DOMAIN NUMERIC(15 COMMENT 'SUB_TYPE TEXT SEGMENT SIZE 80 ', 2) AS NUMERIC(15, 2);

 *//* Table: COMMITTEE, Owner: SYSMANAGER */
CREATE TABLE COMMITTEE (R_OFFICE CHAR(5) NOT NULL,
        COMMITTEE INTEGER NOT NULL,
        COMMITTEE_NAME VARCHAR(50),
        APPLY_BEFORE VARCHAR(10),
        COMMITTEE_TYPE VARCHAR(30),
        CONTACT_NAME VARCHAR(30),
        CONTACT_INITS VARCHAR(5),
        CONTACT_TITLE VARCHAR(5),
        FIRM_NAME VARCHAR(50),
        RANK VARCHAR(30),
        DATE_FORMED DATE,
        FORMED_FOR_PROJECT VARCHAR(10),
        CONSTITUTION VARCHAR(10),
        LEGAL_TYPE VARCHAR(30),
        GOVERNING_STRUCTURE VARCHAR(30),
        LAST_AGM DATE,
        LAST_ELECTION DATE,
        ESTABLISHED VARCHAR(30),
        REPORT_BACKS SMALLINT,
        LAST_REPORT_BACK VARCHAR(30),
        MINUTED_MEETINGS SMALLINT,
        DISABLED_IND CHAR(1) NOT NULL,
        APPLICANT_STEERING VARCHAR(30),
        COMMITTEE_NAME_SHORT VARCHAR(30),
        ORG_CODE INTEGER,
        PERSON_CODE INTEGER,
        USER_GROUP_SET VARCHAR(30),
PRIMARY KEY (R_OFFICE, COMMITTEE));

/* Table: LKP_DISTRICT_COUNCIL, Owner: SYSMANAGER */
CREATE TABLE LKP_DISTRICT_COUNCIL (PROVINCE VARCHAR(30) NOT NULL,
        DISTRICT_COUNCIL VARCHAR(30) NOT NULL,
        DISTRICT_COUNCIL_NAME VARCHAR(80),
        LAT_MAXIMUM NUMERIC(15, 2),
        LAT_MINIMUM NUMERIC(15, 2),
        LONG_MAXIMUM NUMERIC(15, 2),
        LONG_MINIMUM NUMERIC(15, 2),
PRIMARY KEY (PROVINCE, DISTRICT_COUNCIL));


/* Table: PROJECT, Owner: SYSMANAGER */
CREATE TABLE PROJECT (R_OFFICE CHAR(5) NOT NULL,
        COMMITTEE INTEGER NOT NULL,
        PROJECT INTEGER NOT NULL,
        PROJECT_NAME VARCHAR(50),
        PROJECT_REF_NO VARCHAR(15),
        START_DATE DATE,
        COMPLETION_DATE DATE,
        ADJUSTMENT_DAYS SMALLINT,
        OTHER_REFERENCE_NO VARCHAR(15),
        LOCATION BLOB NOT NULL COMMENT 'SUB_TYPE TEXT SEGMENT SIZE 80 ',
        DESCRIPTION BLOB  COMMENT 'SUB_TYPE TEXT SEGMENT SIZE 80',
        DISTANCE SMALLINT,
        PROGRAMME SMALLINT NOT NULL,
        COMPLETE_IND CHAR(1),
        PROVINCE VARCHAR(30),
        LAT_DEG INTEGER,
        LAT_MIN INTEGER,
        RDP_TYPE VARCHAR(50),
        PROVINCE_TYPE VARCHAR(30),
        PROGRAMME_TYPE VARCHAR(30),
        OTHER_PROGRAMME_TYPE VARCHAR(30),
        MOTHER_DEPARTMENT VARCHAR(30),
        HOW_IDENTIFIED VARCHAR(30),
        PROJECT_STATUS SMALLINT,
        PROJECT_ENVIRONMENT VARCHAR(30),
        DISABLED_IND CHAR(1) NOT NULL,
        BUDGET_LOCKED_IND CHAR(1),
        PROJECT_OFFICER VARCHAR(50),
        COMMENT_01 BLOB  COMMENT 'SUB_TYPE TEXT SEGMENT SIZE 80',
        PROJECT_STATUS_DESC VARCHAR(30),
        PROJECT_STATUS_DATE DATE,
        MUNICIPALITY VARCHAR(30),
        CONTACT_NAME VARCHAR(30),
        CONTACT_INITS VARCHAR(5),
        CONTACT_TITLE VARCHAR(5),
        FIRM_NAME VARCHAR(50),
        RANK VARCHAR(30),
        TENDER_NO VARCHAR(30),
        DISTRICT_COUNCIL VARCHAR(30),
        PROJ_GROUP VARCHAR(30),
        NUM_PHASES SMALLINT,
        LAT_SEC INTEGER,
        LONG_SEC INTEGER,
        INITIAL_COST_ESTIMATE NUMERIC(15, 2),
        PROJECT_PRIORITY NUMERIC(15, 2),
        RESPONSIBILITY_CODE INTEGER,
        OBJECTIVE_CODE INTEGER,
        ORG_CODE INTEGER,
        ACTIVE_VARIATION INTEGER DEFAULT 1
,
        VARIATION_LOCKED CHAR(1),
        PERSON_CODE INTEGER,
        LOCKED_IND CHAR(1),
PRIMARY KEY (R_OFFICE, COMMITTEE, PROJECT));

/* Table: R_OFFICE, Owner: SYSMANAGER */
CREATE TABLE R_OFFICE (R_OFFICE CHAR(5) NOT NULL,
        R_OFFICE_NAME VARCHAR(50),
        R_OFFICE_TYPE VARCHAR(10),
        COMMITTEE_CALLED VARCHAR(30),
        R_OFFICE_SHORT_DESC VARCHAR(30),
        DEFAULT_PROVINCE VARCHAR(30),
        DEPARTMENT_ID CHAR(5),
        START_RESPONSIBILITY_CODE INTEGER,
        START_OBJECTIVE_CODE INTEGER,
        CAN_MODIFY_ADDRESS_BOOK CHAR(1),
        PERSON_CODE INTEGER,
        ORG_CODE INTEGER,
        PROJECT_CALLED VARCHAR(30),
        WEBAUTH_PERSON_CODE INTEGER,
        WEBAUTH_ORG_CODE INTEGER,
        WEBAUTH_UNIQUEID VARCHAR(25),
        R_OFFICE_CALLED VARCHAR(30),
PRIMARY KEY (R_OFFICE));

/* Table: REQUIRED_FIELDS, Owner: SYSMANAGER */
CREATE TABLE REQUIRED_FIELDS (PROGRAMME SMALLINT NOT NULL,
        EVENT_TYPE SMALLINT NOT NULL,
        VARIATION SMALLINT NOT NULL,
        SECTION_KEY VARCHAR(30) NOT NULL,
        SECTION_QUALIFIER VARCHAR(30) NOT NULL,
        TABLE_NAME VARCHAR(35) NOT NULL,
        FIELD_NAME VARCHAR(35) NOT NULL,
PRIMARY KEY (PROGRAMME, EVENT_TYPE, VARIATION, SECTION_KEY, SECTION_QUALIFIER, TABLE_NAME, FIELD_NAME));

/*  Index definitions for all user tables */
CREATE INDEX COMM_DISABLED ON COMMITTEE(DISABLED_IND);
CREATE INDEX IDX_OTHER_REF_NO ON PROJECT(OTHER_REFERENCE_NO);
CREATE INDEX IDX_RO_PERSON ON PROJECT(R_OFFICE, PERSON_CODE);
CREATE INDEX PROJ_DISABLED ON PROJECT(DISABLED_IND);
CREATE INDEX PROJ_PROGRAMME ON PROJECT(PROGRAMME);
ALTER TABLE PROJECT ADD FOREIGN KEY (R_OFFICE, COMMITTEE) REFERENCES COMMITTEE(R_OFFICE, COMMITTEE);

/* CREATE GENERATOR RWH_PROJECT_SEQUENCE;

 */;
/* ALTER TABLE REQUIRED_FIELDS ADD
        CHECK (TABLE_NAME = UPPER(TABLE_NAME))
; */
/* ALTER TABLE REQUIRED_FIELDS ADD
        CHECK (FIELD_NAME = UPPER(FIELD_NAME))
; */

/*  Exceptions */

/* CREATE EXCEPTION BADPROJDATES `*Project Start and End Dates are not valid.`;
 */
